### ISSUE TITLE
Is precipitation_amount always missing from last interval?

### ISSUE THREAD

**Issue by FutureSharks** [Rory-Sullivan/metno-locationforecast#1]
H @Rory-Sullivan 

I really like this module and how it's designed, thanks very much for writing it!

A simple question, when I get a forecast, it seems that `precipitation_amount` always missing from last interval. Is that by design?

```
home = Place("Berlin", 52.52437, 13.41053, 34)
forecast = Forecast(home, "")
forecast.update()
```

```
forecast.data.intervals[-2].variables['precipitation_amount']
Variable(precipitation_amount, 0.0, mm)

forecast.data.intervals[-1].variables['precipitation_amount']
KeyError: 'precipitation_amount'
```

**Comment by Rory-Sullivan** [comment]
Hi @FutureSharks 

Thank you, that's much appreciated and apologies for the delay in getting back to you.

This is not really by design it's just that quite often Met Norway do not provide the precipitation data for the last interval. See the below snippet for reference.

![image](https://user-images.githubusercontent.com/61563632/96287643-2603c300-0fda-11eb-93ed-e14af8a8f6f4.png)

Check the files that get saved to your save location to see if this is the case for the data that you are receiving. If you need to check for this before trying to access it, look at the difference between the start and end time on the interval, if it's zero then the precipitation amount won't be there.

**Comment by FutureSharks** [comment]
OK makes sense. Thanks for the answer 🙂
